@startuml
skinparam defaultFontName Microsoft YaHei
skinparam defaultFontSize 16
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam backgroundColor white
class MathTeacher {
+ lecture()
}
class Student {
+ playPiano()
+ writeNovel()
+ learnMath(exercise : string)
}
MathTeacher o-- "1" Student : student / supervises
note bottom of MathTeacher
student.learnMath("exo1")
student.learnMath("exo2")
student.learnMath("exo3")

end note
@enduml
