@startuml
skinparam defaultFontName Microsoft YaHei
skinparam defaultFontSize 16
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam backgroundColor white
abstract class Client
class AnonymousClient
class RegisteredClient {
- email : String
+ getEmail() : String {query}
}
AnonymousClient --|> Client
RegisteredClient --|> Client
@enduml
