@startuml
skinparam defaultFontName Microsoft YaHei
skinparam defaultFontSize 16
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam backgroundColor white
class Bag {
+ applyPromotion(rate : Real)
}
class Item {
+ setPromotion(rate : Real)
}
Bag "0..*" --> "0..*" Item : items
@enduml
