@startuml
skinparam defaultFontName Microsoft YaHei
skinparam defaultFontSize 16
skinparam shadowing false
skinparam backgroundColor white
left to right direction
component "PASS Service" as P
component "Student Directory" as D
component "Marks Storage" as M
() "GradesQuery " as Q
() "StudentLookup" as L
() "MarksQuery" as G
P - Q : 提供
D - L : 提供
M - G : 提供
P ..> L : <<use>>\n需要
P ..> G : <<use>>\n需要
@enduml
