@startuml
skinparam defaultFontName Microsoft YaHei
skinparam defaultFontSize 16
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam backgroundColor white
class Switch {
- state : Boolean
+ toggle() : void
}
class Lamp {
+ on() : void
+ off() : void
+ consumption() : double
}
Switch --> Lamp : lamp
note bottom of Switch
if state then lamp.off()
else lamp.on()

end note
@enduml
